__author__ = "Alexander Matiakubov"
__copyright__ = "Copyright 2020, ISG Neuro"
__license__ = "LICENSE.md"
__version__ = "0.2.0"
__maintainer__ = "Egor Lukyanov"
__email__ = "ma@makuba.ru"
__status__ = "Development"
